linters:
  enable:
    - lll
    - gofumpt

linters-settings:
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 75
    # Tab width in spaces.
    # Default: 1
    tab-width: 1

  gofumpt:
    # Module path which contains the source code being formatted.
    # Default: ""
    module-path: ""
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: false
